### ISSUE TITLE
After modifying the begin position of stack and heap, the tracer become strange

### ISSUE THREAD

**Issue by asesidaa** [ThaumicMekanism/venus#12]
I modified the begin position of heap, stack and static in MemorySegments.kt, the simulator itself works just fine, but the tracer will make the sp, gp and other registers have different values compared with normal simulation, is this a bug or there are other places I need to modify? Thanks!

**Comment by ThaumicMekanism** [comment]
The tracer uses the normal simulation so it should have the correct same values if you modify it. Is this on the java version or the web version that you are seeing an issue.

**Comment by asesidaa** [comment]
For example, I am now setting STACK_BEGIN = 0x000E_FFFF, HEAP_BEGIN = 0x0000_8000, STATIC_BEGIN = 0x0000_3000 and run just addi	x11, zero, 0. On normal simulation, everything works just fine, however, when i use trace, it will set both sp and a1 to 0x000EFFEC and 10 to 0x00000001, and i have no idea where these values come from

**Comment by ThaumicMekanism** [comment]
Those values are argv and argc.
