### ISSUE TITLE
Website venus.cs61c.org incorrect redirection!

### ISSUE THREAD

**Issue by santoslopez** [ThaumicMekanism/venus#25]
Hello. I believe your site have a wrong in redirect! Check in your host DNS redirect. **I believe this is redirect 303 or 301.**

**Example 1**
<img width="980" alt="venus1" src="https://user-images.githubusercontent.com/20478045/160471071-cda8690f-d3a9-4b7e-b6af-c1b19a8e8f85.png">

<img width="980" alt="venus2" src="https://user-images.githubusercontent.com/20478045/160475486-614eea6a-0d2a-469f-a32f-cc5622c70e5a.png">

***redirect wrong***
[http://www.venus.cs61c.org](http://www.venus.cs61c.org)❌
[https://www.venus.cs61c.org](https://www.venus.cs61c.org)❌
[www.venus.cs61c.org](http://www.venus.cs61c.org)❌

***redirect passed***
[http://venus.cs61c.org](http://venus.cs61c.org) ✅ 
[https://venus.cs61c.org](https://venus.cs61c.org) ✅ 
[venus.cs61c.org](http://venus.cs61c.org) ✅

**Comment by ThaumicMekanism** [comment]
Let me talk with the person managing the DNS settings to see if they are able to change it. Was not intended to have something start with www.

Edit: venus is already on a subdomain of cs61c.org so it doesnt really make sense to add www to the front of it.
