### ISSUE TITLE
IllegalStateException: this version of Venus's drive handler ([object Object]) is not compatible with the mounted file server

### ISSUE THREAD

**Issue by FDULeolu** [ThaumicMekanism/venus#26]
I ran `java -jar tools/venus.jar . -dm --port 6162` on local terminal and saw To connect, enter `mount http://localhost:6162 vmfs` on Venus., but when I tried to run `mount http://localhost:6162 vmfs` on Venus terminal, I got an IllegalStateException shown above. What should I do to solve this problem?

**Comment by ThaumicMekanism** [comment]
Make sure you download the latest `venus.jar` file. If this is for CS61C, make sure you get the latest from them and make sure you end up using the correct venus website as they may have modified their version which may prevent it from working on other venus forks.
